language: csharp
mono: none
dotnet: 2.2
solution: AeldreplejeProject.sln

script:
 - dotnet restore
 - dotnet build
 - dotnet test TestCore/TestCore.csproj
 
 # safelist
branches:
  only:
  - Developer